apiVersion: v1
kind: Service
metadata:
  name: runway
  labels:
    app: runway-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80 
      targetPort: 80 
      nodePort: 31089 
      protocol: TCP
  selector:
      app: runway
