apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-example
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: healthy-pod
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 7
          timeoutSeconds: 1
          successThreshold: 3
          failureThreshold: 3