apiVersion: v1
kind: Service
metadata:
  name: k8s-example
  labels:
    app: nginx-service
spec:
  containers:
      - name: healthy-pod
        image: nginx
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 7
    timeoutSeconds: 1
    successThreshold: 3
    failureThreshold: 3