apiVersion: v1
kind: Service
metadata:
  labels:
    app: runaway
  name: runaway
  namespace: game
spec:
  type: NodePort
  ports:
  - name: "runway-service"
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: runaway